### ISSUE TITLE
Improve the messages queue behaviour (with exclusive processing and a controlled retry policy)

### ISSUE THREAD

**Issue by garciparedes** [Clariteia/minos_microservice_networks#179]
* [x] Retry policy to tolerate dispatching exceptions and network failures. #192 
* [x] Transactional consumption through locking column. #190 
* [x] Transactional production through locking column. #201
